graphql:
  servlet:
    mapping: /api/graphql
    enabled: true
    corsEnabled: true

spring:
  jpa:
    properties:
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: true
#      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.enable_lazy_load_no_trans: true


management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
